title: "Naming Conventions — Enterprise Community"
description: "Guida alle convenzioni tecniche per lo sviluppo di applicazioni enterprise"

remote_theme: just-the-docs/just-the-docs@v0.6.2

url: "https://italynewcode.github.io"
baseurl: "/naming-convetion"

lang: it

search_enabled: true

nav_sort: order
heading_anchors: true

footer_content: "Community ItalyNewCode — Contenuto sotto licenza CC BY 4.0"

color_scheme: light

nav_external_links:
  - title: "Repository GitHub"
    url: "https://github.com/ItalyNewCode/naming-convetion"
    hide_icon: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - "*.zip"
